name: first workflow

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
 Dhondumaharaj:
  name: Dhondu Maharaj
  runs-on: dhondu_maharaj
  steps:
   -name: Dhondu maharaj Rocks!
   run: echo Dhondu Maharaj
  

